### ISSUE TITLE
Screen is zoomed in when opening (SteamOS)

### ISSUE THREAD

**Issue by JAWITOR** [ScanMountGoat/ultimate_tex#10] opened 2023-07-25 01:01 UTC
I recently downloaded Ultimate_tex but i’m having an issue where the screen will zoom in where yiu can barely see anything

**Comment by ScanMountGoat** [comment] 2023-07-25 01:23
Do you have a screenshot? What operating system are you using?

**Comment by JAWITOR** [comment] 2023-08-06 23:25
I’m using steam OS

**Comment by ScanMountGoat** [comment] 2023-08-07 14:12
This will be harder for me to reproduce since I don't have any devices running steamos. This may be fixed in a future release if I finish the UI rewrite. There are a lot of scaling issues on different platforms that can be hard to track down.

**Comment by JAWITOR** [comment] 2023-08-08 01:04
Yeah, I was able to get it to work by going into gaming mode on my steam deck

**Comment by ScanMountGoat** [comment] 2023-09-29 18:56
Closing this as the latest version uses a completely different method for drawing the UI.

**Closed by ScanMountGoat** 2023-09-29 18:56 UTC
